sudo: require
services :
  - docker

before_install:
  - docker build -t mjacob/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run mjacob/docker-react-tutorial npm run ci_test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-tutorial"
  env: "DockerReactTutorial-env"
  bucket_name: "elasticbeanstalk-us-east-1-094336088425"
  bucket_path: "docker-react-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
