sudo: require
services :
  - docker

before_install:
  - docker build -t mjacob/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run mjacob/docker-react-tutorial npm run ci_test -- --coverage